spring.application.name=safe-haven-backend

#====In-memory db settings=====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.driverClassName=org.h2.Driver

# login to http://localhost:8080/h2-console with these credentials and url
spring.datasource.url=jdbc:h2:mem:SafeHavenDB
spring.datasource.username=tester
spring.datasource.password=12345

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
#=========